#!/usr/bin/env python

import argparse

from unifi.controller import Controller

parser = argparse.ArgumentParser()
parser.add_argument('-c', '--controller', default='unifi', help='the controller address (default "unifi")')
parser.add_argument('-u', '--username', default='admin', help='the controller usernane (default("admin")')
parser.add_argument('-p', '--password', default='', help='the controller password')
parser.add_argument('-v', '--version', default='v2', help='the controller base version (default "v2")')
parser.add_argument('-s', '--siteid', default='default', help='the site ID, UniFi >=3.x only (default "default")')
parser.add_argument('-m', '--client_mac', default=None, help='the client\'s mac address')
args = parser.parse_args()

from unifi.default_config import load_config 
if not args.password:
    settings = load_config() 
    args.controller = settings['controller_url'].split("//")[1].split(":")[0]
    args.username = settings['controller_credentials']['username']
    args.password = settings['controller_credentials']['password']
    args.version = 'v' + str(settings['version'])
    args.siteid = settings['site_id']

if not args.client_mac:
    raise Exception("must pass mac address")

c = Controller(args.controller, args.username, args.password, version=args.version, site_id=args.siteid)
print("attempting to unauth %s" % args.client_mac) 
c.unauthorize_guest(args.client_mac)
